-- Allow Users to Update Own Profile Documents
-- Generated by Antigravity

-- 1. Ensure the policy exists for users to update their own profile
--    Existing policies might be restrictive (only Managers).
--    We need a policy that allows a user to update specific columns of their own row.
--    In Supabase, we can't restrict columns easily in policies without triggers, 
--    but we can make a broad "update own profile" policy and rely on app logic 
--    OR Supabase's column security if valid (not standard PG RLS).

--    Let's check if there is an existing policy blocking this.
--    Typically "Enable update for users based on email" or similar.

--    For now, we create a policy that simply allows a user to update their own row.
--    If there are restricted columns (like 'role', 'org_id'), we should handle that via a Trigger
--    that prevents changing them if the user is not an admin.
--    (We already added 'check_profile_elevation' trigger in '20240121_fix_join_permissions.sql' 
--    that prevents changing role/org_id/status unless you are a manager or joining).

DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;

CREATE POLICY "Users can update own profile"
ON public.profiles
FOR UPDATE
USING ( auth.uid() = id )
WITH CHECK ( auth.uid() = id );
