-- Add 'documents' column to profiles table
-- Generated by Antigravity to fix "PGRST204: Could not find the 'documents' column"

-- 1. Add the column if it doesn't exist. We use JSONB to store the document URLs (key-value pairs of docType -> url)
ALTER TABLE public.profiles 
ADD COLUMN IF NOT EXISTS documents JSONB DEFAULT '{}'::jsonb;

-- 2. Notify Supabase to reload the schema cache (standard practice implicitly handled by migration runner, but good to note)
-- This migration should cure the 400 Bad Request error.
