-- Fix Storage Policies for 'documents' bucket
-- Generated by Antigravity to resolve "ERROR: 42P01: missing FROM-clause entry for table fs_objects"

-- 1. Create the bucket if it doesn't exist
INSERT INTO storage.buckets (id, name, public) 
VALUES ('documents', 'documents', true) 
ON CONFLICT (id) DO NOTHING;

-- 2. Drop existing policies to avoid conflicts
DROP POLICY IF EXISTS "Allow authenticated uploads" ON storage.objects;
DROP POLICY IF EXISTS "Allow users to view their own documents" ON storage.objects;
DROP POLICY IF EXISTS "Allow users to upload documents" ON storage.objects;
DROP POLICY IF EXISTS "Give users access to own folder 1ok22f_0" ON storage.objects;
DROP POLICY IF EXISTS "Give users access to own folder 1ok22f_1" ON storage.objects;
DROP POLICY IF EXISTS "Give users access to own folder 1ok22f_2" ON storage.objects;
DROP POLICY IF EXISTS "Give users access to own folder 1ok22f_3" ON storage.objects;

-- 3. Policy: Allow Users to Upload to their own folder: "uid/filename"
--    We check that the first folder segment matches their User ID.
CREATE POLICY "Allow users to upload documents"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (
  bucket_id = 'documents' AND
  (storage.foldername(name))[1] = auth.uid()::text
);

-- 4. Policy: Allow Users to View/Select their own documents
CREATE POLICY "Allow users to view their own documents"
ON storage.objects FOR SELECT
TO authenticated
USING (
  bucket_id = 'documents' AND
  (storage.foldername(name))[1] = auth.uid()::text
);

-- 5. Policy: Allow Users to Delete their own documents
CREATE POLICY "Allow users to delete their own documents"
ON storage.objects FOR DELETE
TO authenticated
USING (
  bucket_id = 'documents' AND
  (storage.foldername(name))[1] = auth.uid()::text
);
